[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
quantum_sapiens = "4npWxHiL24QxENfR6k1cs5fXhSJ7RmxeFrMs6fYctDfu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
